In [1]:
import gc
import warnings
warnings.filterwarnings('ignore')
import scipy as sp
import numpy as np
import pandas as pd
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)
from tqdm.auto import tqdm
import itertools
import seaborn as sbn
import matplotlib.pyplot as plt

In [2]:
import sys
sys.path.append('code')

In [3]:
from utils import *

In [4]:
from optimizegrouping import OptmizeGrouping

In [5]:
raw_data = pd.read_csv('data/amex_sample_data.csv')

In [6]:
raw_data.head()

,customer_ID,P_2,D_39,B_1,B_2,R_1,S_3,D_41,B_3,D_42,D_43,D_44,B_4,D_45,B_5,R_2,D_46,D_47,D_48,D_49,B_6,B_7,B_8,D_50,D_51,B_9,R_3,D_52,P_3,B_10,D_53,S_5,B_11,S_6,D_54,R_4,S_7,B_12,S_8,D_55,D_56,B_13,R_5,D_58,S_9,B_14,D_59,D_60,D_61,B_15,S_11,D_62,D_65,B_16,B_17,B_18,B_19,B_20,S_12,R_6,S_13,B_21,D_69,B_22,D_70,D_71,D_72,S_15,B_23,D_73,P_4,D_74,D_75,D_76,B_24,R_7,D_77,B_25,B_26,D_78,D_79,R_8,R_9,S_16,D_80,R_10,R_11,B_27,D_81,D_82,S_17,R_12,B_28,R_13,D_83,R_14,R_15,D_84,R_16,B_29,S_18,D_86,D_87,R_17,R_18,D_88,B_31,S_19,R_19,B_32,S_20,R_20,R_21,B_33,D_89,R_22,R_23,D_91,D_92,D_93,D_94,R_24,R_25,D_96,S_22,S_23,S_24,S_25,S_26,D_102,D_103,D_104,D_105,D_106,D_107,B_36,B_37,R_26,R_27,D_108,D_109,D_110,D_111,B_39,D_112,B_40,S_27,D_113,D_115,D_118,D_119,D_121,D_122,D_123,D_124,D_125,D_127,D_128,D_129,B_41,B_42,D_130,D_131,D_132,D_133,R_28,D_134,D_135,D_136,D_137,D_138,D_139,D_140,D_141,D_142,D_143,D_144,D_145,B_30,B_38,D_114,D_116,D_117,D_120,D_126,D_63,D_64,D_66,D_68,target
0,0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...,0.934745,0.009119,0.009382,1.007647,0.006104,0.135021,0.001604,0.007174,NaN,NaN,0.003258,0.070793,0.740102,0.231717,0.008309,0.420521,0.539715,0.192376,NaN,0.149564,0.058425,0.002927,0.153461,0.673522,0.009535,0.000085,0.203524,0.629392,0.326101,NaN,0.034643,0.010260,0.001770,1.008097,0.008517,0.105671,0.112294,0.488232,0.187285,0.166636,0.100107,0.009444,0.007174,0.007397,0.010239,0.063465,0.258461,0.227637,0.014553,0.402246,0.446568,0.008656,0.006408,NaN,1.007897,0.005274,0.007630,0.184036,0.003945,0.686719,0.005375,0.005469,0.008050,0.008254,0.377991,0.006970,0.304625,0.040367,NaN,0.006564,0.001298,0.001352,NaN,0.002230,0.009162,0.421334,0.006475,0.001068,0.000747,0.002193,0.006345,NaN,0.000026,0.208253,0.001057,0.009351,0.007236,0.009177,0.507423,0.006550,1.002178,0.084745,0.006099,0.000013,0.002902,0.001115,0.001911,0.003256,NaN,0.001277,0.009968,NaN,0.002330,0.002517,NaN,1,0.003511,0.008099,0.007645,0.009411,0.006355,0.008501,1.007528,0.004638,0.001445,0.003080,1.006011,0.003641,0.004638,0.003866,0.005909,0.005458,0.001190,0.917811,0.131801,0.936067,0.971994,0.001281,0.943340,1.002457,1.014510,1.073985,NaN,0.671683,0.007441,0.008676,NaN,1.006130,NaN,0.000226,NaN,NaN,NaN,1.009372,0.100454,0.928955,0.003658,0.255787,0.260255,0.256656,0.719791,0.433844,0.003580,0.684978,0.008398,1.008338,0.999737,1.008523,0.003973,NaN,0.004186,0.005702,NaN,0.006210,0.002715,NaN,NaN,NaN,NaN,NaN,0.007186,0.004234,0.005086,NaN,0.005810,0.002970,0.008533,0.0,2.0,1.0,0.0,4.0,0.0,1.0,CR,O,NaN,6.0,0
1,00000fd6641609c6ece5454664794f0340ad84dddce9a2...,0.880519,0.178126,0.034684,1.004028,0.006911,0.165509,0.005552,0.005068,NaN,0.060646,0.008781,0.020626,0.266275,0.027000,0.004976,0.438828,0.402195,0.014696,NaN,0.167634,0.028411,0.000974,NaN,0.339683,0.012926,0.102036,0.242366,0.570898,0.297130,NaN,0.043929,0.014570,0.002911,1.002821,0.003283,0.208516,0.019050,0.406434,0.036112,0.748383,0.017684,0.005880,0.009756,0.127805,0.018667,0.212538,0.411989,0.048978,0.009538,0.363754,0.233980,0.008747,0.002940,NaN,1.003602,0.008047,0.004319,0.192371,0.007744,0.287101,0.006190,0.007636,0.006174,0.000883,0.007636,0.001278,0.304711,0.014705,NaN,0.004659,0.007925,0.009600,NaN,0.002383,0.008256,0.227755,0.021153,0.000182,0.001542,0.009117,0.006892,NaN,0.006931,0.002119,0.002046,0.009664,0.005375,0.005009,NaN,0.005414,1.008568,0.019672,0.006197,0.005370,0.006271,0.009911,0.000983,0.006669,NaN,0.009298,0.006460,NaN,0.006503,0.007052,NaN,1,0.005091,0.001838,0.008645,0.009467,0.003500,0.000473,1.000766,0.004864,0.000907,0.003830,0.009166,0.004641,0.000195,0.000523,0.006421,0.004975,0.002397,0.920889,0.132865,0.930629,0.977674,0.003213,0.001621,0.008952,0.004363,NaN,NaN,0.007774,0.007457,0.032899,NaN,1.007599,NaN,0.004743,NaN,NaN,NaN,1.006547,0.019811,0.292214,0.009312,0.454329,0.446036,0.436884,0.551341,0.286821,0.008603,0.136650,0.009314,0.000229,0.999252,0.001777,0.002943,NaN,0.002202,0.001928,NaN,0.002996,0.001701,NaN,NaN,NaN,NaN,NaN,0.002980,0.007479,0.007870,NaN,0.003284,0.003169,0.008514,0.0,2.0,1.0,0.0,-1.0,0.0,1.0,CO,O,NaN,6.0,0
2,00001b22f846c82c51f6e3958ccd81970162bae8b007e8...,0.880875,0.009704,0.004284,0.812650,0.006450,NaN,0.003796,0.007196,NaN,NaN,0.000628,0.031044,0.251598,0.001557,0.001687,0.433713,0.339125,0.080370,NaN,0.183628,0.026981,0.000247,NaN,0.342118,0.009392,0.006264,0.202159,0.628938,0.296313,NaN,0.001824,0.005092,1.002366,1.005992,0.001983,NaN,0.007158,0.009188,0.098963,0.209386,0.001749,0.003000,0.002847,NaN,0.006699,0.213039,0.002820,0.137834,0.006031,0.280417,0.438647,0.000845,0.007836,NaN,1.004080,0.005951,0.002835,0.190958,0.008575,0.006706,0.000036,0.009486,0.002793,0.006101,0.015025,0.008889,0.506746,0.020228,NaN,0.002699,0.002067,0.003329,NaN,0.000552,0.006740,0.407122,0.007427,0.009752,0.002990,0.006786,0.006549,NaN,0.009305,0.000931,0.006391,0.005349,0.005475,0.000167,NaN,0.000159,1.004567,0.030023,0.005352,0.003245,0.002310,0.005328,0.009366,0.006171,NaN,0.001763,0.004081,NaN,0.005628,0.003440,NaN,1,0.006258,0.009829,0.001252,0.009926,0.004965,0.008178,1.000779,0.004868,0.004085,0.001122,0.009410,0.002195,0.003562,0.003742,0.000170,0.004746,0.009617,0.302868,0.132692,0.086479,0.972368,0.004705,0.009786,0.003091,0.005433,NaN,NaN,0.000847,0.005196,0.004723,NaN,1.003010,NaN,0.009816,NaN,NaN,NaN,1.007076,0.024902,NaN,0.000257,0.388621,0.368051,0.369018,0.444615,0.149832,0.004057,0.275856,0.004732,0.009514,0.008331,0.004189,0.004133,NaN,0.002654,0.003470,NaN,0.009881,0.007691,NaN,NaN,NaN,NaN,NaN,0.007383,0.006623,0.000964,NaN,0.002202,0.000834,0.003444,0.0,1.0,1.0,0.0,-1.0,0.0,1.0,CO,R,NaN,6.0,0
3,000041bdba6ecadd89a52d11886e8eaaec9325906c9723...,0.621776,0.001083,0.012564,1.006183,0.007829,0.287766,0.004532,0.009937,NaN,0.046104,0.007792,0.007235,0.085103,0.118818,0.004238,0.410723,0.414224,0.013057,NaN,0.174331,0.011969,1.005561,0.430318,0.333342,0.020526,0.204338,0.198356,0.672080,0.411625,0.001379,0.022970,0.005491,0.001113,1.004073,0.008534,0.279464,0.074835,0.170538,0.021400,0.554483,0.055897,0.001347,0.009294,0.011429,0.017101,0.509411,0.394758,0.026844,0.002199,0.368774,0.434503,0.008578,0.089177,1.007434,1.007289,0.007715,0.008557,0.054633,0.000952,0.423241,0.004447,0.004894,0.000993,0.006015,0.010685,0.006446,0.508872,0.005060,NaN,0.007902,0.004011,0.005505,NaN,0.008794,0.006096,0.401139,0.014266,0.004983,0.007304,0.000659,0.005665,NaN,0.006713,0.005918,0.007501,0.507283,0.007924,0.008404,NaN,0.007657,1.009117,0.010497,0.005440,0.001881,0.006133,0.001680,0.005498,0.507532,NaN,0.000482,0.001864,NaN,0.000843,0.009902,NaN,1,0.005235,0.008212,0.007541,0.007374,0.009349,0.002196,1.009480,0.008491,0.003347,0.005297,0.509612,0.002310,0.009715,0.003028,0.009486,0.008072,0.006325,0.931634,0.132833,0.957105,0.974041,0.043710,0.002448,0.002433,0.004051,NaN,NaN,0.008019,0.004745,0.007375,NaN,1.004479,NaN,0.008627,NaN,NaN,NaN,1.003711,0.031024,0.680603,0.205291,0.059353,0.058773,0.062736,0.629147,0.290245,0.009977,0.594160,0.004466,0.009322,1.002652,1.001869,0.004254,NaN,0.000060,0.004576,NaN,0.001789,0.005140,NaN,NaN,NaN,NaN,NaN,0.002704,0.006184,0.001899,NaN,0.008183,0.005560,0.002983,0.0,2.0,1.0,0.0,6.0,0.0,1.0,CO,O,NaN,3.0,0
4,00007889e4fcd2614b6cbe7f8f3d2e5c728eca32d9eb8a...,0.871900,0.005573,0.007679,0.815746,0.001247,0.176403,0.000231,0.005528,NaN,0.044671,0.002436,0.269407,0.069952,0.004855,0.001991,0.465525,0.480303,0.325121,NaN,0.048857,0.159818,1.005185,0.095238,0.003557,0.004027,0.000050,0.253811,0.570419,0.125195,NaN,0.009350,0.001001,1.007410,1.007116,0.001858,0.122915,0.013041,0.008594,0.254067,0.183075,0.006051,0.008859,0.382744,NaN,0.009469,0.488844,0.002670,0.600739,0.005842,0.326776,0.422841,0.001734,0.005095,NaN,0.531486,0.006706,0.008807,0.185639,0.003575,0.009251,0.009527,0.008175,0.009727,0.001121,0.016457,0.001375,0.503735,0.145214,NaN,0.009202,0.144073,0.142552,NaN,0.009507,0.006455,0.392566,0.009528,0.005802,0.007474,0.005898,0.006559,NaN,0.007571,0.407653,0.005454,0.009085,0.001414,0.003912,NaN,0.007245,1.008890,0.250254,0.000740,0.007172,0.006752,0.000947,0.007841,0.003264,NaN,0.000467,0.009311,NaN,0.005307,0.003116,NaN,1,0.005995,0.009058,0.007263,0.002803,0.006336,0.000266,1.007604,0.006980,0.005827,0.006047,0.006960,0.002473,0.001454,0.009854,0.004971,0.002976,0.001382,0.297843,0.132099,0.081818,0.971905,0.002345,0.589246,1.004867,0.963496,0.809463,NaN,1.006895,0.002269,0.007787,NaN,1.006920,NaN,0.001815,NaN,NaN,NaN,1.008149,0.116816,NaN,0.002960,0.448481,0.442338,0.436173,0.565815,0.435161,0.003628,0.181963,0.000091,0.007207,1.006172,1.008584,0.001068,NaN,1.006119,0.008897,NaN,0.005045,0.003706,NaN,NaN,NaN,NaN,NaN,0.002974,0.004162,0.005764,NaN,0.008154,0.006944,0.000905,0.0,1.0,1.0,0.0,4.0,0.0,1.0,CO,O,1.0,6.0,0

In [7]:
raw_data.shape

(8294, 190)

In [8]:
raw_data[raw_data.B_2.isnull()]

,customer_ID,P_2,D_39,B_1,B_2,R_1,S_3,D_41,B_3,D_42,D_43,D_44,B_4,D_45,B_5,R_2,D_46,D_47,D_48,D_49,B_6,B_7,B_8,D_50,D_51,B_9,R_3,D_52,P_3,B_10,D_53,S_5,B_11,S_6,D_54,R_4,S_7,B_12,S_8,D_55,D_56,B_13,R_5,D_58,S_9,B_14,D_59,D_60,D_61,B_15,S_11,D_62,D_65,B_16,B_17,B_18,B_19,B_20,S_12,R_6,S_13,B_21,D_69,B_22,D_70,D_71,D_72,S_15,B_23,D_73,P_4,D_74,D_75,D_76,B_24,R_7,D_77,B_25,B_26,D_78,D_79,R_8,R_9,S_16,D_80,R_10,R_11,B_27,D_81,D_82,S_17,R_12,B_28,R_13,D_83,R_14,R_15,D_84,R_16,B_29,S_18,D_86,D_87,R_17,R_18,D_88,B_31,S_19,R_19,B_32,S_20,R_20,R_21,B_33,D_89,R_22,R_23,D_91,D_92,D_93,D_94,R_24,R_25,D_96,S_22,S_23,S_24,S_25,S_26,D_102,D_103,D_104,D_105,D_106,D_107,B_36,B_37,R_26,R_27,D_108,D_109,D_110,D_111,B_39,D_112,B_40,S_27,D_113,D_115,D_118,D_119,D_121,D_122,D_123,D_124,D_125,D_127,D_128,D_129,B_41,B_42,D_130,D_131,D_132,D_133,R_28,D_134,D_135,D_136,D_137,D_138,D_139,D_140,D_141,D_142,D_143,D_144,D_145,B_30,B_38,D_114,D_116,D_117,D_120,D_126,D_63,D_64,D_66,D_68,target
7455,042a81bae597726cf7122265ab1533e99866af050f9e54...,NaN,0.000428,0.13237,NaN,0.00951,0.162972,NaN,NaN,NaN,NaN,NaN,0.052984,NaN,0.003952,0.007544,NaN,-0.020009,NaN,NaN,NaN,0.562362,1.00908,NaN,0.004785,0.330949,0.001967,NaN,NaN,-0.002549,NaN,0.002724,0.088684,0.003589,NaN,0.003644,0.158783,0.008355,0.459279,NaN,NaN,NaN,0.006729,0.176515,NaN,0.016766,NaN,0.211709,0.748341,0.005476,0.404578,0.005044,0.000966,NaN,NaN,0.695085,NaN,NaN,0.192958,0.002799,0.428465,0.009607,NaN,NaN,NaN,0.010251,NaN,0.306661,0.427738,NaN,0.965895,0.222463,0.205481,NaN,0.009044,0.005041,0.009484,0.03071,NaN,NaN,NaN,0.00051,NaN,0.006916,0.000062,0.004974,0.000232,NaN,NaN,NaN,0.005902,1.007496,0.03321,0.002173,NaN,0.003066,0.000888,NaN,0.005386,NaN,0.004299,0.004538,NaN,0.00298,0.008718,NaN,1,0.003775,0.00686,0.006191,0.009958,0.008524,0.000001,NaN,NaN,0.009417,0.009238,NaN,0.009234,0.004146,0.002826,0.004963,0.00511,0.00454,0.893345,0.134007,0.923124,0.973375,0.008443,0.001428,NaN,NaN,NaN,NaN,NaN,0.007513,0.137556,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.133811,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.009925,NaN,NaN,0.003236,NaN,NaN,NaN,NaN,0.004557,0.006571,NaN,NaN,NaN,NaN,NaN,NaN,0.009297,NaN,NaN,NaN,0.009251,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,CO,NaN,NaN,NaN,0

In [10]:
cc = OptmizeGrouping(data=raw_data, xname='D_41', yname='target')
cc.coarsebin_interval()

Warning: Please Check missing value ! All of them = 1 or = 0

                                           D_41_bins  Good  Bad  Total     %Good      %Bad    %Total  Bad_Rate       WOE        IV      Odds
0                        1. ( -inf, 0.001152588048 ]   348   67    415  0.060438  0.031589  0.052672  0.161446  0.648807  0.018717  5.194030
1            2. (  0.001152588048 , 0.002354993952 ]   677  153    830  0.117576  0.072136  0.105343  0.184337  0.488531  0.022199  4.424837
2     3. (  0.002354993952 , 0.0035396404080000016 ]   687  142    829  0.119312  0.066950  0.105216  0.171291  0.577805  0.030255  4.838028
3  4. (  0.0035396404080000016 , 0.16841496520000...  3669  892   4561  0.637200  0.420556  0.578881  0.195571  0.415506  0.090017  4.113229
4  5. (  0.16841496520000077 , 0.34285927679999983 ]   215  200    415  0.037339  0.094295  0.052672  0.481928 -0.926382  0.052763  1.075000
5                 6. (  0.34285927679999983 , True ]   126  288    414  0.021883  0.135785  0.052545  0.695652 -1.825381  0.207915  0.437500
6                           7. (  True , 4.8956385 ]    36  379    415  0.006252  0.178689  0.052672  0.913253 -3.352720  0.578133  0.094987

In [11]:
feats = ["P_2", "D_39", "B_1", "B_2", "R_1", "S_3", "D_41"]

In [12]:
from IPython.display import display
for var in feats:
    print(var)
    cc = OptmizeGrouping(data=raw_data, xname=var, yname='target', mingroupsize=0.03)
    res = cc.coarsebin_interval()
    display(res)

P_2

                   P_2_bins  Good   Bad  Total     %Good      %Bad    %Total  Bad_Rate       WOE        IV        Odds
0                      Null    37     9     46  0.006104  0.004942  0.005835  0.195652  0.211039  0.000245    4.111111
1         1. ( -inf, True ]  5615  1810   7425  0.926262  0.993959  0.941900  0.243771 -0.070539  0.004775    3.102210
2  2. (  True , 1.0098933 ]   410     2    412  0.067634  0.001098  0.052264  0.004854  4.120356  0.274153  205.000000

D_39

                   D_39_bins  Good   Bad  Total    %Good      %Bad    %Total  Bad_Rate       WOE        IV      Odds
0  1. ( -inf, 0.9143725813 ]  5719  1746   7465  0.99409  0.820874  0.947335  0.233891  0.191458  0.033163  3.275487
1   3. (  True , 3.3825579 ]    34   381    415  0.00591  0.179126  0.052665  0.918072 -3.411448  0.590916  0.089239

B_1

                   B_1_bins  Good   Bad  Total     %Good      %Bad    %Total  Bad_Rate       WOE        IV      Odds
0         1. ( -inf, True ]  5579  1886   7465  0.977229  0.868724  0.947335  0.252646  0.117695  0.012771  2.958112
1  2. (  True , 1.3240526 ]   130   285    415  0.022771  0.131276  0.052665  0.686747 -1.751811  0.190080  0.456140

B_2
Warning: Please Check missing value ! All of them = 1 or = 0

                   B_2_bins  Good   Bad  Total     %Good      %Bad    %Total  Bad_Rate       WOE        IV       Odds
0         1. ( -inf, True ]  3298  1678   4976  0.549667  0.893028  0.631552  0.337219 -0.485306  0.166635   1.965435
1  2. (  True , 1.0099936 ]  2702   201   2903  0.450333  0.106972  0.368448  0.069239  1.437423  0.493556  13.442786

R_1

                                      R_1_bins  Good  Bad  Total     %Good      %Bad    %Total  Bad_Rate       WOE        IV      Odds
0                  1. ( -inf, 0.004335850075 ]  2039  450   2489  0.354547  0.211367  0.315863  0.180796  0.517246  0.074059  4.531111
1        2. (  0.004335850075 , 0.0061436873 ]  1049  195   1244  0.182403  0.091592  0.157868  0.156752  0.688872  0.062557  5.379487
2  3. (  0.0061436873 , 0.007247137760000001 ]   665  164    829  0.115632  0.077031  0.105203  0.197829  0.406199  0.015680  4.054878
3   4. (  0.007247137760000001 , 0.254181684 ]  1713  361   2074  0.297861  0.169563  0.263198  0.174060  0.563402  0.072283  4.745152
4            5. (  0.254181684 , 0.504462408 ]   145  270    415  0.025213  0.126820  0.052665  0.650602 -1.615410  0.164137  0.537037
5                   6. (  0.504462408 , True ]   113  301    414  0.019649  0.141381  0.052538  0.727053 -1.973444  0.240232  0.375415
6                      7. (  True , 2.507711 ]    27  388    415  0.004695  0.182245  0.052665  0.934940 -3.658890  0.649637  0.069588

S_3

                                     S_3_bins  Good  Bad  Total     %Good      %Bad    %Total  Bad_Rate       WOE        IV       Odds
0                                        Null   987   71   1058  0.171742  0.032479  0.133367  0.067108  1.665386  0.231926  13.901408
1            1. ( -inf, 0.13077769849999998 ]  1311  137   1448  0.228119  0.062672  0.182529  0.094613  1.291960  0.213752   9.569343
2  2. (  0.13077769849999998 , 0.1725020911 ]  1676  495   2171  0.291630  0.226441  0.273667  0.228006  0.253003  0.016493   3.385859
3  3. (  0.1725020911 , 0.36322253569999996 ]  1350  821   2171  0.234905  0.375572  0.273667  0.378167 -0.469268  0.066010   1.644336
4          4. (  0.36322253569999996 , True ]   306  417    723  0.053245  0.190759  0.091138  0.576763 -1.276106  0.175483   0.733813
5                    5. (  True , 2.5810466 ]   117  245    362  0.020358  0.112077  0.045632  0.676796 -1.705689  0.156443   0.477551

D_41
Warning: Please Check missing value ! All of them = 1 or = 0

                                           D_41_bins  Good  Bad  Total     %Good      %Bad    %Total  Bad_Rate       WOE        IV      Odds
0                        1. ( -inf, 0.001152588048 ]   348   67    415  0.060438  0.031589  0.052672  0.161446  0.648807  0.018717  5.194030
1            2. (  0.001152588048 , 0.002354993952 ]   677  153    830  0.117576  0.072136  0.105343  0.184337  0.488531  0.022199  4.424837
2     3. (  0.002354993952 , 0.0035396404080000016 ]   687  142    829  0.119312  0.066950  0.105216  0.171291  0.577805  0.030255  4.838028
3  4. (  0.0035396404080000016 , 0.16841496520000...  3669  892   4561  0.637200  0.420556  0.578881  0.195571  0.415506  0.090017  4.113229
4  5. (  0.16841496520000077 , 0.34285927679999983 ]   215  200    415  0.037339  0.094295  0.052672  0.481928 -0.926382  0.052763  1.075000
5                 6. (  0.34285927679999983 , True ]   126  288    414  0.021883  0.135785  0.052545  0.695652 -1.825381  0.207915  0.437500
6                           7. (  True , 4.8956385 ]    36  379    415  0.006252  0.178689  0.052672  0.913253 -3.352720  0.578133  0.094987

In [12]:
xname = 'D_63'
target = 'target'

In [13]:
dataset=raw_data[[xname,target]]

In [14]:
crosstab_dt = pd.crosstab(raw_data['D_63'], raw_data['target'], margins=True)

In [15]:
crosstab_dt = pd.crosstab(raw_data['D_63'], raw_data['target'], margins=True)
crosstab_dt.columns = ['Good', "Bad", 'All']
crosstab_dt.fillna(0, inplace=True)
crosstab_dt.reset_index(inplace=True)

In [16]:
crosstab_dt

  D_63  Good   Bad   All
0   CL   419   219   638
1   CO  4483  1702  6185
2   CR  1123   247  1370
3   XL    13     6    19
4   XM    15     8    23
5   XZ    43    16    59
6  All  6096  2198  8294

In [17]:
crosstab_dt['%All'] = crosstab_dt.All / crosstab_dt.All.sum()
crosstab_dt['bad_rate'] = crosstab_dt.Bad / crosstab_dt.All

In [18]:
crosstab_dt.sort_values('%All', inplace=True)
crosstab_dt.reset_index(inplace=True, drop=True)
# crosstab_dt['group'] = ['seg_' + str(i) for i in range(len(crosstab_dt))]

In [19]:
crosstab_dt

  D_63  Good   Bad   All      %All  bad_rate
0   XL    13     6    19  0.001145  0.315789
1   XM    15     8    23  0.001387  0.347826
2   XZ    43    16    59  0.003557  0.271186
3   CL   419   219   638  0.038462  0.343260
4   CR  1123   247  1370  0.082590  0.180292
5   CO  4483  1702  6185  0.372860  0.275182
6  All  6096  2198  8294  0.500000  0.265011

In [21]:
cc = OptmizeGrouping(data=raw_data, xname='D_63', yname='target')
cc.coarsebin_norminal()

   CutPoint  Good   Bad  Total     %Good      %Bad    %Total  Bad_Rate       WOE        IV      Odds
0  0.180292  1123   247   1370  0.184219  0.112375  0.165180  0.180292  0.494286  0.035512  4.546559
1  0.271186    43    16     59  0.007054  0.007279  0.007114  0.271186 -0.031474  0.000007  2.687500
2  0.275182  4483  1702   6185  0.735400  0.774340  0.745720  0.275182 -0.051597  0.002009  2.633960
3  0.315789    13     6     19  0.002133  0.002730  0.002291  0.315789 -0.246895  0.000147  2.166667
4  0.343260   419   219    638  0.068734  0.099636  0.076923  0.343260 -0.371286  0.011474  1.913242
5  0.347826    15     8     23  0.002461  0.003640  0.002773  0.347826 -0.391476  0.000462  1.875000

In [ ]:
dataset = raw_data[[xname, target]]

In [ ]:
raw_data.D_68.fillna(7, inplace=True)

In [ ]:
dataset['weight'] = raw_data.D_68

In [ ]:
dataset['const'] = 1

In [ ]:
pd.crosstab(dataset['D_63'], dataset['target'], values=dataset.const, aggfunc='sum',margins=True)

In [ ]:
crosstab_dt = pd.crosstab(dataset['D_63'], dataset['target'], values=dataset.weight, aggfunc='sum')

In [ ]:
crosstab_dt.columns = ['Good', "Bad"]

In [ ]:
crosstab_dt.reset_index('D_63', inplace=True)

In [ ]:
crosstab_dt

In [ ]:
for val in list(set(dataset[xname])):
        dataset.loc[dataset[xname] == val, 'CutPoint'] = dataset.loc[(dataset[xname] == val) & (dataset[target] == 1)]['weight'].sum()/dataset.loc[dataset[xname] == val]['weight'].sum()

In [ ]:
dataset.head()

In [ ]:
dataset.weight.sum()

In [ ]:
dist_x_vals = len(set(dataset[xname]))

In [ ]:
dist_x_vals

In [ ]:
from eda import *

In [ ]:
categorical_analysis_plot(df=raw_data,
                          categorical_var="S_3_woe",
                          target='target'
                         )

In [ ]:
numerical_analysis_plot(raw_data=raw_data,
                          numerical_var="P_2",
                          target='target'
                         )